[package]
name = "septid"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
aes-ctr = "0.3"
byteorder = "1"
crypto-mac = "0.7"
digest = "0.8"
getopts = "0.2"
mio = "0.6"
ring = "0.14"
sha2 = "0.8"
hmac = "0.7"
num-bigint = "0.2"
num-traits = "0.2"
subtle = "2"

[dependencies.failure]
default-features = false
features = ["std"]
version = "0.1"

[dependencies.pbkdf2]
default-features = false
version = "0.3"

[dependencies.signal-hook]
features = ["mio-support"]
version = "0.1"
